### ISSUE TITLE
cannot perform upload operation on <input> elements with type="file"

### ISSUE THREAD

**Issue by firdausng** [theintern/leadfoot#121]
```js
this.remote.find(type,value).type()
```

above code give the error below

```
Error: This method has been removed in JSZip 3.0, please check the upgrade guide.
      at JSZip.generate  <node_modules\jszip\lib\object.js:311:15>
      at <node_modules\src\Element.ts:97:20>
      at new Task  <node_modules\@dojo\core\async\Task.ts:210:3>
      at Element._uploadFile  <node_modules\src\Element.ts:92:9>
      at Element.type  <node_modules\src\Element.ts:282:17>
      at Command.<anonymous>  <node_modules\src\Command.ts:555:17>
      at <node_modules\@dojo\core\async\Task.ts:319:12>
      at handler  <node_modules\@dojo\core\async\ExtensiblePromise.ts:216:14>
      at <anonymous>
      at process._tickCallback  <internal\process\next_tick.js:169:7>
      at Command._callElementMethod  <node_modules\src\Command.ts:549:9>
      at Command.type  <node_modules\src\Command.ts:1348:14>
      at Function.<anonymous>  <test\ui\pom\reprisesxa.admin.clients\reprisesxa.admin.clients.ts:26:100>
      at step  <node_modules\tslib\tslib.js:122:27>
      at Object.next  <node_modules\tslib\tslib.js:103:57>
      at fulfilled  <node_modules\tslib\tslib.js:93:62>
      at <anonymous>
```

**Comment by jason0x43** [comment]
It looks like we're missing some test coverage since this wasn't caught when the code was switched from jszip 2.5 to 3.1.

We should update to use the proper API (`generateAsync` or `generateNodeStream`) and ensure we have a unit (preferably) or functional test that exercises this.
