### ISSUE TITLE
Unhandled rejection for IE 11 on Command#get

### ISSUE THREAD

**Issue by jason0x43** [theintern/leadfoot#132]
IE 11 with Leadfoot 2.0.1, Intern 4.1.1, Selenium 3.4.1, IE Driver 3.4.0 is throwing an unhandled rejection from `Server#post`. I've seen both ECONNREFUSED and ECONNRESET. In either case, it should be handled.

```
Unhandled rejection: { [POST http://localhost:4444/wd/hub/session/dc5cf19d-f9c8-4387-8585-2910236d5479/url] connect ECONNREFUSED 127.0.0.1:4444
    at Server.post (C:\Users\Jason\Temp\intern-ie\node_modules\@theintern\leadfoot\Server.js:200:21)
    at runRequest (C:\Users\Jason\Temp\intern-ie\node_modules\@theintern\leadfoot\Session.js:74:53)
    at Task_1.default.cancelled (C:\Users\Jason\Temp\intern-ie\node_modules\@theintern\leadfoot\Session.js:85:52)
    at new Task (C:\Users\Jason\Temp\intern-ie\node_modules\@dojo\core\async\Task.js:73:17)
    at InitializedProxiedSession.Session._delegateToServer (C:\Users\Jason\Temp\intern-ie\node_modules\@theintern\leadfoot\Session.js:62:16)
    at InitializedProxiedSession.Session.serverPost (C:\Users\Jason\Temp\intern-ie\node_modules\@theintern\leadfoot\Session.js:93:21)
    at InitializedProxiedSession.Session.get (C:\Users\Jason\Temp\intern-ie\node_modules\@theintern\leadfoot\Session.js:163:21)
    at C:\Users\Jason\Temp\intern-ie\node_modules\intern\lib\ProxiedSession.js:48:45
    at C:\Users\Jason\Temp\intern-ie\node_modules\@dojo\core\async\Task.js:194:165
    at C:\Users\Jason\Temp\intern-ie\node_modules\@dojo\core\async\Task.js:228:28
    at Command._callSessionMethod (C:\Users\Jason\Temp\intern-ie\node_modules\@theintern\leadfoot\Command.js:300:16)
    at Command.get (C:\Users\Jason\Temp\intern-ie\node_modules\@theintern\leadfoot\Command.js:351:21)
    at Test.it [as test] (C:\Users\Jason\Temp\intern-ie\tests\functional.js:8:7)
    at C:\Users\Jason\Temp\intern-ie\node_modules\intern\lib\Test.js:179:36
    at C:\Users\Jason\Temp\intern-ie\node_modules\@dojo\core\async\Task.js:220:28
    at handler (C:\Users\Jason\Temp\intern-ie\node_modules\@dojo\core\async\ExtensiblePromise.js:126:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4444 } Promise {
  <rejected> { [POST http://localhost:4444/wd/hub/session/dc5cf19d-f9c8-4387-8585-2910236d5479/url] connect ECONNREFUSED 127.0.0.1:4444
    at Server.post (C:\Users\Jason\Temp\intern-ie\node_modules\@theintern\leadfoot\Server.js:200:21)
    at runRequest (C:\Users\Jason\Temp\intern-ie\node_modules\@theintern\leadfoot\Session.js:74:53)
    at Task_1.default.cancelled (C:\Users\Jason\Temp\intern-ie\node_modules\@theintern\leadfoot\Session.js:85:52)

**Comment by jason0x43** [comment]
False alarm.
