### ISSUE TITLE
Edge `clearCookies()` should no longer be a 'known defect'?

### ISSUE THREAD

**Issue by gitgrimbo** [theintern/leadfoot#163]
https://github.com/theintern/leadfoot/blob/a8fbfe7ffc3e7efdb85c7f31a8a3204085ae9ad9/src/Server.ts#L588

I don't think this is true any more for `clearCookies()` on:

Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134
Driver 17134

In my test:

```js
    afterEach: function() {
      // Clear cookies to return to clean state for other tests
      const dfd = this.async();
      console.log("brokenDeleteCookie", this.remote.session.capabilities.brokenDeleteCookie);
      this.remote.session.capabilities.brokenDeleteCookie = false;
      console.log("brokenDeleteCookie", "override", this.remote.session.capabilities.brokenDeleteCookie);
      this.remote
        .getCookies()
        .then((function(cookies) {
          console.log("COOKIES before", cookies);
        }))
        .clearCookies()
        .then(function() {
          return this.session.getCookies()
            .then((function(cookies) {
              console.log("COOKIES after", cookies);
            }));
        })
        .catch((err) => console.log(err))
        .finally(() => dfd.resolve());
    },
```

output:

```
brokenDeleteCookie true
brokenDeleteCookie override false
COOKIES before [ { name: 'previewCols',
    value: 'url%20status%20size%20uncompressedSize%20timeline',
    path: '/webapp/',
    domain: 'harviewer.lan',
    expiry: null,
    secure: false,
    httpOnly: false },
  { name: 'validate',
    value: 'true',
    path: '/webapp/',
    domain: 'harviewer.lan',
    expiry: null,
    secure: false,
    httpOnly: false } ]
COOKIES after []
```

**However** this required a patch of `getCookies()`, because Edge driver 17134 returns `null` if there are no cookies, so ensure there is at least an empty array:

https://github.com/theintern/leadfoot/blob/a8fbfe7ffc3e7efdb85c7f31a8a3204085ae9ad9/src/Session.ts#L938

```js
return (cookies || []).map(function(badCookie) {
```

**Comment by gitgrimbo** [comment]
But after commenting out `brokenDeleteCookie` in `Server.ts`:

```js
      // MS Edge has broken cookie deletion.
      //updates.brokenDeleteCookie = true;
```

when I run the Leadfoot self-tests I see an error:

```
D:\dev\git_repos\intern\leadfoot>npm test config=@edge grep=cookies

> @theintern/leadfoot@2.3.0-pre test D:\dev\git_repos\intern\leadfoot
> intern "config=@edge" "grep=cookies"

Listening on localhost:9000 (ws 9001)
Tunnel started

‣ Created remote session MicrosoftEdge on windows 10 (59C9C3AB-0C7F-40E9-8462-EE7E6D976A7C)
× MicrosoftEdge on windows 10 - Session - cookies (#getCookies, #setCookie, #clearCookies, #deleteCookie) (0.058s)
    UnknownError: [DELETE http://localhost:4444/wd/hub/session/59C9C3AB-0C7F-40E9-8462-EE7E6D976A7C/cookie] Unknown error
      at Server.delete  <src\Server.ts:18:0>
      at runRequest  <src\Session.ts:132:10>
      at <src\Session.ts:164:42>
      at new e  <node_modules\@theintern\common\index.js:16:5076>
      at Session._delegateToServer  <src\Session.ts:110:11>
      at Session.serverDelete  <src\Session.ts:178:16>
      at Session.clearCookies  <src\Session.ts:1051:16>
      at <tests\functional\Session.ts:932:27>
      at <node_modules\@theintern\common\index.js:16:7261>
      at process._tickCallback  <internal\process\next_tick.js:68:7>
```

Not sure why `clearCookies()` works in my app's test, but not Leadfoot's self-tests.

**Comment by gitgrimbo** [comment]
More investigation.

Checking out `2.2.3` of the Leadfoot repo, and updating its deps to Intern `4.2.3`:

```
     "@theintern/dev": "~0.9.0",
     "@types/jszip": "~3.1.4",
-    "@types/node": "~9.6.5",
-    "concurrently": "~3.5.0",
-    "intern": "~4.2.3"
+    "@types/node": "~10.12.0",
+    "concurrently": "~4.0.1",
+    "intern": "~4.3.3"
   },
```

The self-tests fail, but if I add a sleep to the cookie test, and use the printed session id to curl the DELETE cookie endpoint, it works. Yet the DELETE command from within the test fails.

Again, commenting out MS Edge cookie feature:

```js
      // MS Edge has broken cookie deletion.
      //updates.brokenDeleteCookie = true;
```

### tests/functional/Session.ts

```js
        console.log(session._sessionId);
        return session
          .get('tests/functional/data/default.html')
          .then(function() {
            return new Command(session).sleep(15 * 1000);
          })
          .then(function() {
            return session.setCookie({ name: 'foo', value: '1=3' });
          })
          .then(function() {
            console.log("clearCookies", 1);
            return session.clearCookies();
          })
```

### console

self-test fails with `Unknown Error`.

`delete session/71955155-1499-45B1-A147-E3C43F6E46DF/cookie undefined undefined` is `method, path, requestData, pathParts` from `_delegateToServer()`.

```
71955155-1499-45B1-A147-E3C43F6E46DF
clearCookies 1
delete session/71955155-1499-45B1-A147-E3C43F6E46DF/cookie undefined undefined
error 1 { [DELETE http://localhost:4444/wd/hub/session/71955155-1499-45B1-A147-E3C43F6E46DF/cookie] Unknown error
    at Server.delete (D:\dev\git_repos\intern\leadfoot\_build\src\Server.js:95:2971)
    at runRequest (D:\dev\git_repos\intern\leadfoot\_build\src\Session.js:32:341)
    at D:\dev\git_repos\intern\leadfoot\_build\src\Session.js:48:247
    at new e (D:\dev\git_repos\intern\leadfoot\node_modules\@theintern\common\index.js:16:5076)
    at Session._delegateToServer (D:\dev\git_repos\intern\leadfoot\_build\src\Session.js:25:637)
    at Session.serverDelete (D:\dev\git_repos\intern\leadfoot\_build\src\Session.js:48:887)
    at Session.clearCookies (D:\dev\git_repos\intern\leadfoot\_build\src\Session.js:281:219)
    at D:\dev\git_repos\intern\leadfoot\_build\tests\functional\Session.js:631:36
    at D:\dev\git_repos\intern\leadfoot\node_modules\@theintern\common\index.js:16:7182
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'UnknownError',
  message:
   '[DELETE http://localhost:4444/wd/hub/session/71955155-1499-45B1-A147-E3C43F6E46DF/cookie] Unknown error',
  status: 13,
  detail: { message: 'Unknown error' },
  request:
   { url:
      'http://localhost:4444/wd/hub/session/71955155-1499-45B1-A147-E3C43F6E46DF/cookie',
     method: 'DELETE',
     data: undefined },
  response:
   t {
     listenersMap: Map {},
     handles: [],
     response:
      { status: 200,
        statusText: 'OK',
        headers: [Object],
        config: [Object],
        request: [ClientRequest],
        data:
         '{"sessionId":"71955155-1499-45B1-A147-E3C43F6E46DF","status":13,"value":{"message":"Unknown error"}}' },
     headersAccessor: e { data: [Object] },
     stringValue:
      '{"sessionId":"71955155-1499-45B1-A147-E3C43F6E46DF","status":13,"value":{"message":"Unknown error"}}' } }
```

### curl

While the test above is sleeping, using the session id printed above (`71955155-1499-45B1-A147-E3C43F6E46DF`), curl gets a valid response:

```json
{"sessionId":"71955155-1499-45B1-A147-E3C43F6E46DF","status":0,"value":null}
```

I can run the curl command multiple times while the test is sleeping and get the same valid response.

```
Paul@Ryzen5 MINGW64 /d/dev/git_repos/harviewer2 (dev)
$ WD_SESSION_ID=71955155-1499-45B1-A147-E3C43F6E46DF
$ curl --verbose http://localhost:4444/wd/hub/session/${WD_SESSION_ID}/cookie

$ curl --verbose http://localhost:4444/wd/hub/session/${WD_SESSION_ID}/cookie
* Uses proxy env variable no_proxy == '192.168.99.100'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 4444 (#0)
> GET /wd/hub/session/71955155-1499-45B1-A147-E3C43F6E46DF/cookie HTTP/1.1
> Host: localhost:4444
> User-Agent: curl/7.60.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Cache-Control: no-cache
< Server: Microsoft-HTTPAPI/2.0
< Date: Thu, 25 Oct 2018 09:35:16 GMT
< Content-Type: application/json;charset=utf-8
< Content-Length: 76
<
{ [76 bytes data]
100    76  100    76    0     0   4750      0 --:--:-- --:--:-- --:--:--  4750{"sessionId":"71955155-1499-45B1-A147-E3C43F6E46DF","status":0,"value":null}
* Connection #0 to host localhost left intact
```
