### ISSUE TITLE
Running the leadfoot tests with Edge gives errors

### ISSUE THREAD

**Issue by gitgrimbo** [theintern/leadfoot#165]
Windows 10. Checked-out master branch.

Command: `npm run build && npm test config=@edge`.

Snip from `intern.json`:

```
    "edge": {
      "tunnel": "selenium",
      "tunnelOptions": {
        "version": "3.12.0",
        "drivers": [
          {
            "name": "edge",
            "version": "17134"
          }
        ]
      },
      "environments": [ { "browserName": "MicrosoftEdge" } ]
    },
```

Output:

```
‣ Created remote session MicrosoftEdge on windows 10 (1C626818-13B6-4FF8-B13A-F31C7962FC8F)
× MicrosoftEdge on windows 10 - Element - #click (0.057s)
    AssertionError: expected undefined to be an array
      at <tests\functional\Element.ts:477:19>
      at <node_modules\@theintern\common\index.js:16:7182>
      at process._tickCallback  <internal\process\next_tick.js:68:7>

× MicrosoftEdge on windows 10 - Element - #isSelected (drop-down) - change selection (0.018s)
    AssertionError: Newly selected element should be selected: expected false to be true
      at <tests\functional\Element.ts:811:27>
      at <node_modules\@theintern\common\index.js:16:7182>
      at process._tickCallback  <internal\process\next_tick.js:68:7>

× MicrosoftEdge on windows 10 - leadfoot/helpers/pollUntil - early timeout (0.173s)
    AssertionError: expected 'Timeout' to equal 'ScriptTimeout'

    A Timeout
    E ScriptTimeout

      at Command.<anonymous>  <tests\functional\helpers\pollUntil.ts:81:21>
      at runCallback  <src\Command.ts:573:35>
      at Command.<anonymous>  <src\Command.ts:603:19>
      at <node_modules\@theintern\common\index.js:16:7261>
      at process._tickCallback  <internal\process\next_tick.js:68:7>
      at Command.then  <src\Command.ts:594:11>
      at Test.early timeout [as test]  <tests\functional\helpers\pollUntil.ts:76:11>
      at <src\lib\Test.ts:260:47>
      at <node_modules\@dojo\core\async\Task.ts:351:12>
      at handler  <node_modules\@dojo\core\async\ExtensiblePromise.ts:229:14>
      at process._tickCallback  <internal\process\next_tick.js:68:7>

× MicrosoftEdge on windows 10 - helpers/pollUntilTruthy - early timeout (0.17s)
    AssertionError: expected 'Timeout' to equal 'ScriptTimeout'

    A Timeout
    E ScriptTimeout

      at Command.<anonymous>  <tests\functional\helpers\pollUntilTruthy.ts:68:21>
      at runCallback  <src\Command.ts:573:35>
      at Command.<anonymous>  <src\Command.ts:603:19>
      at <node_modules\@theintern\common\index.js:16:7261>
      at process._tickCallback  <internal\process\next_tick.js:68:7>
      at Command.then  <src\Command.ts:594:11>
      at Test.early timeout [as test]  <tests\functional\helpers\pollUntilTruthy.ts:63:11>
      at <src\lib\Test.ts:260:47>
      at <node_modules\@dojo\core\async\Task.ts:351:12>
      at handler  <node_modules\@dojo\core\async\ExtensiblePromise.ts:229:14>
      at process._tickCallback  <internal\process\next_tick.js:68:7>

× MicrosoftEdge on windows 10 - Session - cookies (#getCookies, #setCookie, #clearCookies, #deleteCookie) (0.061s)
    AssertionError: Clearing cookies should cause no cookies to exist: expected [ Array(1) ] to have a length of 0 but got 1
      at <tests\functional\Session.ts:864:19>
      at <node_modules\@theintern\common\index.js:16:7182>
      at process._tickCallback  <internal\process\next_tick.js:68:7>

× MicrosoftEdge on windows 10 - Session - #pressKeys (0.039s)
    AssertionError: expected '' to equal 'hello, world'

    E hello, world

      at <tests\functional\Session.ts:1505:19>
      at <node_modules\@theintern\common\index.js:16:7182>
      at process._tickCallback  <internal\process\next_tick.js:68:7>
```

**Comment by jason0x43** [comment]
Edge has never passed all the tests, but it's been a while since I looked at its specific issues. Time to re-evaluate...
