### ISSUE TITLE
BrowserStack devices are not working

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [theintern/leadfoot#22]
Hi,

I'm using Intern in my project to test our application over 40 different setups, but for some reason I always get this error when testing devices in BrowserStack and the test is not being executed while OS X and Windows works fine.

```
UnknownCommand: [POST http://(redacted)@hub.browserstack.com:4444/wd/hub/session / {"desiredCapabilities":{"device":"iPhone 5s","platform":"MAC","browserName":"iPhone","browserstack.local":"true","browserstack.localIdentifier":"1111111111111","name":"test/intern-browserstack.js","idle-timeout":60,"selenium-version":"2.39.0","project":"MyProject"}}] The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.
at Server._post  <node_modules/leadfoot/Server.js:68:9>
at Server.createSession  <node_modules/leadfoot/Server.js:291:15>
at Suite.setup  <node_modules/intern/runner.js:223:22>
at callOnSuite  <node_modules/intern/lib/Suite.js:157:42>
at call  <node_modules/intern/lib/Suite.js:208:13>
at Suite.run  <node_modules/intern/lib/Suite.js:306:4>
at <node_modules/intern/main.js:54:18>
at <node_modules/intern/lib/util.js:325:19>
at Array.forEach  <native>
at Object.run  <node_modules/intern/main.js:53:16>
```

The environment is configured following the BrowserStack capabilities:

```js
{ 'device' : 'iPhone 5s', 'platform': 'MAC', 'browserName': 'iPhone' }
```

The device is getting booted in BrowserStack but nothing is ever getting loaded and I need to stop the session manually.

Many thanks!

p.s. I don't know if this is a Leadfoot, Intern of BrowserStack issue so correct me if this is the wrong project for this issue.

**Comment by csnover** [comment]
Is this still an issue?

**Comment by ChristiaanScheermeijer** [comment]
I don't know actually, we don't use BrowserStack for mobile testing anymore since we ran into multiple issues.

**Comment by jason0x43** [comment]
Closing this due to inactivity
