### ISSUE TITLE
The FirefoxDriver cannot be used after quit() was called

### ISSUE THREAD

**Issue by jonashaag** [theintern/leadfoot#87]
With intern:

Testing works, but Firefox driver complains about being used after `quit()` was called. I don't have minimal reproducing example at this point, but may be able to craft one if absolutely necessary.

I'm not calling `quit()` anywhere in my code.

```
TOTAL: tested 1 platforms, 0/1 tests failed
10:08:42.835 WARN - Exception thrown
org.openqa.selenium.remote.SessionNotFoundException: The FirefoxDriver cannot be used after quit() was called.
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'b1c642276166', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.15-moby', java.version: '1.8.0_102'
Driver info: driver.version: EventFiringWebDriver
at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.execute(FirefoxDriver.java:377)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:316)
at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:103)
at com.sun.proxy.$Proxy1.get(Unknown Source)
at org.openqa.selenium.support.events.EventFiringWebDriver.get(EventFiringWebDriver.java:163)
at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:40)
at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:1)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
10:08:42.837 WARN - Exception: The FirefoxDriver cannot be used after quit() was called.
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'b1c642276166', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.15-moby', java.version: '1.8.0_102'
Driver info: driver.version: EventFiringWebDriver
```

**Comment by jason0x43** [comment]
Are you returning a promise chain from your tests? This kind of issue could happen if a promise wasn't returned from a test. Intern could end up closing the session while a chain of remote commands was still active.

**Comment by jonashaag** [comment]
Oh, that seems to be the issue. Is there a way that we can recognise this error in intern and print a nice warning message?

**Comment by jason0x43** [comment]
There was another request similar to this in the last few months, although I don't recall whether it was here or in Intern. On the one hand, it's not an error to not return a promise from an Intern test (that just means it's a synchronous test). On the other hand, there is a case to be made for having Intern assume that any functional test is asynchronous.

**Comment by jason0x43** [comment]
Ah, yes, it was https://github.com/theintern/intern/pull/552

**Comment by jason0x43** [comment]
Closing as this was handled in the above referenced issue.
