### ISSUE TITLE
Simulated mouse and keyboard events broken in Firefox 49

### ISSUE THREAD

**Issue by rodneyrehm** [theintern/leadfoot#98]
possibly a duplicate of #91 - although I'm just running Firefox 49 with default settings on BrowserStack.

```
TypeError: event.initKeyboardEvent is not a function
```

It looks like [simulateKeys()](https://github.com/theintern/leadfoot/blob/master/Session.js#L197-L212) is failing in in Firefox. That's likely because [KeyboardEvent.initKeyboardEvent()](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/initKeyboardEvent) is deprecated in favor for the [KeyboardEvent constructor](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent).

The same is probably also true for [dispatchInput()](https://github.com/theintern/leadfoot/blob/master/Session.js#L214-L218) and [simulateMouse()](https://github.com/theintern/leadfoot/blob/master/Session.js#L264-L285).

Maybe [simulant.js](https://github.com/Rich-Harris/simulant) is an option?

```
Firefox 49 on WIN: JavaScriptError: [POST https://(redacted)@hub.browserstack.com:443/wd/hub/session/<session>/execute / {"script":"return (function simulateKeys(keys) {\n\tvar target = document.activeElement;\n\n\tfunction dispatch(kwArgs) {\n\t\tvar event = document.createEvent('KeyboardEvent');\n\t\tevent.initKeyboardEvent(\n\t\t\tkwArgs.type,\n\t\t\tkwArgs.bubbles || true,\n\t\t\tkwArgs.cancelable || false,\n\t\t\twindow,\n\t\t\tkwArgs.key || '',\n\t\t\tkwArgs.location || 3,\n\t\t\tkwArgs.modifiers || '',\n\t\t\tkwArgs.repeat || 0,\n\t\t\tkwArgs.locale || ''\n\t\t);\n\n\t\treturn target.dispatchEvent(event);\n\t}\n\n\tfunction dispatchInput() {\n\t\tvar event = document.createEvent('Event');\n\t\tevent.initEvent('input', true, false);\n\t\treturn target.dispatchEvent(event);\n\t}\n\n\tkeys = Array.prototype.concat.apply([], keys.map(function (keys) {\n\t\treturn keys.split('');\n\t}));\n\n\tfor (var i = 0, j = keys.length; i < j; ++i) {\n\t\tvar key = keys[i];\n\t\tvar performDefault = true;\n\n\t\tperformDefault = dispatch({ type: 'keydown', cancelable: true, key: key });\n\t\tperformDefault = performDefault && dispatch({ type: 'keypress', cancelable: true, key: key });\n\n\t\tif (performDefault) {\n\t\t\tif ('value' in target) {\n\t\t\t\ttarget.value = target.value.slice(0, target.selectionStart) + key +\n\t\t\t\t\ttarget.value.slice(target.selectionEnd);\n\t\t\t\tdispatchInput();\n\t\t\t}\n\t\t\telse if (target.isContentEditable) {\n\t\t\t\tvar node = document.createTextNode(key);\n\t\t\t\tvar selection = window.getSelection();\n\t\t\t\tvar range = selection.getRangeAt(0);\n\t\t\t\trange.deleteContents();\n\t\t\t\trange.insertNode(node);\n\t\t\t\trange.setStartAfter(node);\n\t\t\t\trange.setEndAfter(node);\n\t\t\t\tselection.removeAllRanges();\n\t\t\t\tselection.addRange(range);\n\t\t\t}\n\t\t}\n\n\t\tdispatch({ type: 'keyup', cancelable: true, key: key });\n\t}\n}).apply(this, arguments);","args":[[""]]}] TypeError: event.initKeyboardEvent is not a functio
n (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10 milliseconds
Build info: version: '3.0.0-beta2', revision: '2aa21c1', time: '2016-08-02 15:03:28 -0700'
System info: host: '185-129-70-248', ip: '185.129.70.248', os.name: 'windows', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{browserstack.finalTunnelFork=sqv6cEvYhs8zryrhvxUP-1479160330734, browserstack.localIdentifier=1479160330734, raisesAccessibilityExceptions=false, browserstack.tunnelIdentifier=1479160330734, language=dojo/2.0.0-dev Node.js/4.4.2, browserstack.selenium.jar.version=3.0.0-beta2, appBuildId=20160916101415, platform=XP, browserstack.local=true, specificationLevel=0, acceptSslCerts=false, processId=4336, browser=firefox, browserVersion=49.0, platformVersion=6.3, acceptSslCert=false, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, idle-timeout=60, browser_version=49.0, platformName=windows_nt, 64bit=true, browserstack.debug=false, rotatable=false, browserstack.forksUsed=false, os=WINDOWS, browserstack.ie.noFlash=false, os_version=8.1, version=49.0, proxy={}, command_id=1, firefox_binary=c:\Program Files (x86)\firefox 49.0\firefox.exe, browserstack.video=true, orig_os=win8.1, takesElementScreenshot=true, chromeOptions={args=[--multiple-automatic-downloads=1, test-type, --disable-application-cache, --media-cache-size=1, --disk-cache-size=1], prefs={browser={show_update_promotion_info_bar=false, check_default_browser=false}, profile={password_manager_enabled=false}, devtools={preferences={cacheDisabled=true}}}}, device=desktop, firefox_profile=UEsDBBQAAAAIADNwWUmK7I+M9AMAA..., proxy_type=privoxy}]
Session ID: <session-id>
at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
at ProxiedSession.Session.execute  <node_modules/intern/node_modules/leadfoot/Session.js:643:21>
at ProxiedSession.Session.pressKeys  <node_modules/intern/node_modules/leadfoot/Session.js:1317:16>
at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:635:19>
at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
at Command.target.(anonymous function) [as pressKeys]  <node_modules/intern/node_modules/leadfoot/Command.js:610:11>
at Test.test  <test/functional/prepare.js:24:10>
at <node_modules/intern/lib/Test.js:184:24>
at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
at nextTickCallbackWith0Args  <node.js:420:9>
at process._tickCallback  <node.js:349:13>
```

**Comment by jason0x43** [comment]
Yeah, `initKeyboardEvent` doesn't exist in Firefox (at least not now). Oddly enough, `initMouseEvent` does. In any case, a fix (along with some other geckodriver updates) is in progress.

**Comment by rodneyrehm** [comment]
Is there any way I can help resolve this problem?

**Comment by jason0x43** [comment]
Leadfoot 1.7.0 (used by Intern 3.4.2) now uses the KeyboardEvent and MouseEvent constructors if they exist, so this should be resolved. Are you still seeing the issue?

**Comment by rodneyrehm** [comment]
The `initKeyboardEvent` error seems to be resolved. However, my tests are failing. I assume this is because the simulated events (here <kbd>Tab</kbd>) do not trigger browser functionality (here *advance focus to next element in tab order*).

Is it possible that the test determining if the browser supports "native events" began failing for Firefox some time after version 44?

**Comment by rodneyrehm** [comment]
Haven't seen any more issues with Firefox 50 and Intern 3.4.2
